# Site
title:              CAECOM
bio:                'Centro Acadêmico de Engenharia de Computação - UNIVASF.'
description:        "Página do Centro Acadêmico de Engenharia de Computação da UNIVASF."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
logo_text:          'assets/img/logo-texto-aecom.png'
background:         'assets/img/placeholders/cup-of-coffee-1280537_1920.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             pt_BR
url:                # https://caecom.github.io/
maintena:           true   # Mudar para true se quiser exibir mensagem de manutenção na página inicial.

# Jekyll
permalink:          /:categories/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
# disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              univasf.caecom@gmail.com
#twitter:            username
facebook:           groups/CAECOM
github-url:         caecom
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
telegramgroup:     CAECOM_UNIVASF
telegramchannel:   CAECOM_NEWS

# Plugins - (old Gems)
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com
  
# Collections
collections:
  guias:
    output: true
    permalink: /:collection/:title/
  links:
    link: true

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
